### PR TITLE
Allow the format string of the formatters to be set by the user.

### PR DESCRIPTION
**Pull request by gmdvieira**
Every squadron has a different way to report BGS activity. This change allows the user to customize the format string of the formatters.

The current stage of this pull request has only the user facing changes in the preferences dialog.

### CODE REVIEW

**Comment by gmdvieira** [comment]
Here is the proposal for format string in the preference dialog. If you like it, I can continue to develop this branch.

My plan is to store the format strings as a dictionary, in the tracker serialized in settings.json, much like the minor faction list is stored. There is some plumbing involved, specially regarding instantiating the formatters and defaults.

**Comment by anthonylangsworth** [comment]
I like the direction. Things that immediately come to mind (which I am sure you are thinking of, too, and I am happy to contribute to or write) include:
1. Validation and error reporting: We want any format string errors to be reported before the "OK" button is clicked on the EDMC Settings dialog. If the user presses "OK" with an invalid format string, we need to show an informative error message, such as in the main EDMC window.
2. Help: We want users to understand the format strings, including the syntax and available options. One solution is to link to a help document hosted here, with the source code on GitHub.
3. Back end enhancements: We may need to calculate other values in the back end. For example, the `MarketSellEventSummary` may have to calculate multiple totals like total trades, total credits, total tonnes, etc. This can be a subsequent release or pull request.
4. Automated testing: We want testing to be as automatable as possible. Therefore, as much of this should be outside `load.py` as possible.

**Comment by gmdvieira** [comment]
> * Validation and error reporting: We want any format string errors to be reported before the "OK" button is clicked on the EDMC Settings dialog. If the user presses "OK" with an invalid format string, we need to show an informative error message, such as in the main EDMC window.

I did not think of validating before the OK! This would be ideal. More complex but doable.

Solid error reporting during activity creation is inevitable. Output the error in place of the string will show it to the user *and* can be tested! Will follow this road first. We can expand the UI later. 

> 
> * Help: We want users to understand the format strings, including the syntax and available options. One solution is to link to a help document hosted here, with the source code on GitHub.

That's what I was thinking. Put a placeholder link in the UI. Have to write it.

> 
> * Back end enhancements: We may need to calculate other values in the back end. For example, the `MarketSellEventSummary` may have to calculate multiple totals like total trades, total credits, total tonnes, etc. This can be a subsequent release or pull request.

That's the plan all along. :innocent: 

> 
> * Automated testing: We want testing to be as automatable as possible. Therefore, as much of this should be outside `load.py` as possible.

Even with room for improvement, I consider the UI side of things done. From now on mostly everything will be outside load.py and tested.

By the way, I've looked the way the tracker is serialized and how load.py handles it. There is one thing I don't understand: the "config" object. It seems to be only read and deleted, not written. Doesn't seem to be a standard Python class. I'm stumped. Can you give me some pointers?

**Comment by anthonylangsworth** [comment]
> By the way, I've looked the way the tracker is serialized and how load.py handles it. There is one thing I don't understand: the "config" object. It seems to be only read and deleted, not written. Doesn't seem to be a standard Python class. I'm stumped. Can you give me some pointers?

`config` is the standard EDMC config object. See https://github.com/EDCD/EDMarketConnector/blob/main/PLUGINS.md#configuration for details.

You are correct in that `load.py` never writes to `config`. Early versions of EDMFAT stored details like the selected minor factions in config. This was simple and followed the EDMC pattern. However, when I started serializing the mission summaries so they were not wiped after closing EDMC, the data quickly exceeded the 8K recommended limit for Windows registry values.

Therefore, I moved everything to the `settings.json` file rather than store configuration in multiple places. This change meant I could store data in a structured, e.g. hierarchical or object-based, way. It also made debugging easier - a user could send me their `settings.json` file and I would see everything. 

However, I want to clean up any old values to prevent clutter and confusion. Therefore, I ensure I delete any old config values on load and whenever I save the settings. There are still old versions of the plug-in so I cannot remove them just yet. I may do so one day.

**Comment by gmdvieira** [comment]
Just pushed the serialization, storage and restore of the formatter strings. I've created a new version of the serializer, to import old versions of a serialized tracker cleanly. Also updated the serializer tests. Defined the default formatter strings.

Next step is to actually use the formatter strings in the formatter.

**Comment by gmdvieira** [comment]
Unfortunately, I wont be able to see this change through at this time. Thanks for your patience!

**Comment by anthonylangsworth** [comment]
I understand. It is a big ask. Thanks for offering to help.

Is there anything I can do or should have done to make this easier?

**Comment by gmdvieira** [comment]
> Is there anything I can do or should have done to make this easier?

No, thanks. Actually, working the code was no problem at all. Just a bunch of other stuff to do. Scratched my itch, that's all. See ya!

**Pull request closed without merging**
