### PR TITLE
Add Update 10 trade changes + Format for PEP8

### PR DESCRIPTION
**Pull request by anthonylangsworth**
@gmdvieira This may interest you because it will impact your other pull request, particularly the PEP8 reformat. Consequently, I am happy to help merge the changes into your branch. Otherwise, your feedback is welcome.

Update 10 Trade Changes
----------------------------

Frontier Developments released Update 10 for Odyssey and Horizons on 25 Jan 2022. The [release notes](https://forums.frontier.co.uk/threads/update-10-odyssey-and-horizons.597956/) included:

> - Faction consequences from selling commodities are now based on satisfying available demand at the Commodity Market
>   - You can now support a faction by buying commodities from it, based upon satisfying available supply at its Commodity Market
>   - When buying and selling, it's generally more positive to a faction to satisfy a higher supply and demand (green 3-bar icon) than a lower (red 1-bar icon), and it's generally more positive to trade more expensive commodities than cheaper ones

As with all BGS changes in **Elite Dangerous**, the exact changes are ambiguous and unknown. Therefore, the code changes present more information about the trade, including the average value of the supply and demand brackets. Presumably, this is the supply and demand "bracket", a number from 0 to 3 represented in the in-game user interface as bars, as implied by the last bullet point. I assume this is not the supply or demand value, a count of T of the commodity. This also satisfies #1.

The old way of reporting market sell events was `X T trade at Y CR average profit per T` where **X** was the total T traded and **Y** average profile or loss per T. The new way is `A market sell(s). Total: B T and C CR profit. Average: D CR/T profit at bracket E` where **A** is the count of market sell events, B is the total T sold, C the total CR profile or less, D the average profit or loss per T and E is the average demand bracket. Market buy events follow a similar format and were not previously reported because they were not BGS-impacting.

The code treats any buy and a profitable sale as supporting or PRO the owning minor faction. The code still treats an unprofitable trade as undermining or ANTI the owning minor faction. Further testing will help refine this and I expect further changes to both refine the output and improve the PRO/ANTI accuracy.

PEP8 Code Reformat
-----------------------

I reformatted the code to be consistent with PEP8. I have saved the lining rules used for flake8 in `.flake8`. This ensures consistent formatting today and in the future.

Minor Changes
-----------------

Changed the help text in the plug-in's settings tab to mention the 'Available Minor Factions' list box by name. This makes it explicit and, therefore, less confusing to some.

### CODE REVIEW

**Comment by gmdvieira** [comment]
This is awesome! The trade report is very informative, specially considering that nothing is known about the current state of trade for influence (and it is exactly what I was looking for in my first patch!).

After you merge it, I will rebase my branch on top of it and do the PEP8 dance. Thanks for making me aware of flake8. I'm an old guy, last time I did any meaningful work with Python was in the 2.4 era. (Also I saw you excluded long lines, tsk tsk tsk, :stuck_out_tongue:) 

I have two comments. 1) You changed the serializing code and kept the version number. I guess this will make users upgrading loose their configuration. Take a look at the last commit of my open pull request. 2) The market.json load is Windows only. This isn't important; I do all my work (including EDMFAT) in Linux, but play ED in Windows. But, I want to let you know.

**Comment by gmdvieira** [comment]
> Yes, I should have fixed the long times, too. I got lazy. Expect them to be fixed soon.

Oh, please, don't. I was joking. Really. You're anything but lazy.  
 
> Regarding your first comment about serialization, the only change to the serialized JSON is the addition of the demand bracket field for market sell events. When deserializing, if the field is omitted, it assumes 0. This should make it backwards compatible with the need to increment the version number.

Great, I did not know that. 

> 
> Regarding your second comment about market.json being Windows only, I did not know what. Is there a code change that will make it work on Linux or other operating systems?

I checked how EDMarketConnector does it. Unfortunately there is no default place for these files on Linux, so it is user configurable. The good news is that we can use the EDMC user configuration:
```
    journal_dir = config.default_journal_dir
```
For context, see https://github.com/EDCD/EDMarketConnector/blob/d8b29e45b86f36ab3cf540ec1503b9170a8505de/monitor.py#L184

I haven't tested, so not sure if this helps.

**Comment by anthonylangsworth** [comment]
> > Yes, I should have fixed the long times, too. I got lazy. Expect them to be fixed soon.
> 
> Oh, please, don't. I was joking. Really. You're anything but lazy.

Thanks. However, I should fix the line lengths. They are hard to read.

> ```
>         journal_dir = config.get_str('journaldir')
> ```
> 
> For context, see https://github.com/EDCD/EDMarketConnector/blob/d8b29e45b86f36ab3cf540ec1503b9170a8505de/monitor.py#L181
> 
> This should be portable, because EDMC does the heavy lifting. I haven't tested, so not sure if this works.

I wondered whether there was a shortcut for that. Thanks! I shall test it and, if it works, add it to the code.

**Comment by anthonylangsworth** [comment]
Alas, `config.get_str('journaldir')` returns an empty string on Windows. Checking the registry, `HKEY_CURRENT_USER\Software\Marginal\EDMarketConnector` contains a value `journaldir` but it is an empty string. It may be set on non-Windows systems. I have kept the code commented out in there in case you find it useful.

**Comment by gmdvieira** [comment]
Aha! That's why the EDMC code is like this:
```
        journal_dir = config.get_str('journaldir')

        if journal_dir == '' or journal_dir is None:
            journal_dir = config.default_journal_dir
```
Because on Windows the user won't set a journaldir.

**Comment by anthonylangsworth** [comment]
The other problem is it pulls `config` into that file, which breaks all the unit tests because it is not found. I need to find a way to bypass the failed import to get automated tests work. There is probably something obvious.

**Comment by anthonylangsworth** [comment]
... and hopefully rectified now.

**Pull request merged**
